### ISSUE TITLE
1.0.3无法正常运行运行

### ISSUE THREAD

**Issue by daisybaicai** [sl1673495/react-antd-treetable#2]
相关版本
    "umi": "^3.4.1",
    "antd": "^4.15.0",
    "react-antd-treetable": "^1.0.3"

```
devScripts.js:6523 [@umijs/runtime] load component failed Error: Module "./react-antd-treetable" does not exist in container.
while loading "./react-antd-treetable" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:682 
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umijs_runtime_dist_index_esm_js.95b96b1e.async.js:408:68)
    at Route
    at Switch
    at Authorized (http://localhost:8000/umi.js:5336:23)
    at main
    at Basic (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.401378f0.async.js:378:25)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.401378f0.async.js:361:66)
    at ConfigProviderWrap (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-provider_es_index_js-node_modules_ant-design_pro-utils_es-f22a39.3ce17755.async.js:335:23)
    at WrapContent (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es_alert_style_index-c74c0f.9e1dd626.async.js:1440:21)
    at div
    at section
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.401378f0.async.js:393:63)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.401378f0.async.js:361:66)
    at div
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_alert_ErrorBoundary_js-node_modules_antd_es_alert_index_js-node_-578a5c.2c62d72b.async.js:406:31)
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_antd_es_alert_style_index-c74c0f.9e1dd626.async.js:675:66)
    at BasicLayout (http://localhost:8000/layouts__BasicLayout.js:1281:24)
    at ConnectFunction (http://localhost:8000/mf-dep_vendors-node_modules_dva_dist_index_esm_js.1bc04f3b.async.js:3387:68)
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umijs_runtime_dist_index_esm_js.95b96b1e.async.js:408:68)
    at Route
    at Switch
    at SecurityLayout (http://localhost:8000/layouts__SecurityLayout.js:54:5)
    at ConnectFunction (http://localhost:8000/mf-dep_vendors-node_modules_dva_dist_index_esm_js.1bc04f3b.async.js:3387:68)
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umijs_runtime_dist_index_esm_js.95b96b1e.async.js:408:68)
    at Route
    at Switch
    at Inspector (http://localhost:8000/mf-dep_vendors-node_modules_react-dev-inspector_es_index_js.0d4299bc.async.js:1055:20)
    at Layout (http://localhost:8000/layouts__BlankLayout.js:28:23)
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules_umijs_runtime_dist_index_esm_js.95b96b1e.async.js:408:68)
    at Route
    at Switch
    at Router (http://localhost:8000/mf-dep_vendors-node_modules_react-router-dom_esm_react-router-dom_js.336fcc02.async.js:2526:30)
    at RouterComponent (http://localhost:8000/mf-dep_vendors-node_modules_umijs_renderer-react_dist_index_esm_js.b5adcd4d.async.js:529:23)
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules_dva_dist_index_esm_js.1bc04f3b.async.js:3101:20)
    at _DvaContainer (http://localhost:8000/umi.js:1633:5)
    at http://localhost:8000/umi.js:2134:24
    at FormProvider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.8572e7fa.async.js:3803:31)
    at LocaleProvider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.8572e7fa.async.js:448:87)
    at ProviderChildren (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.8572e7fa.async.js:280:24)
    at LocaleReceiver (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_context_js.95899783.async.js:718:87)
    at ConfigProvider (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js.8572e7fa.async.js:388:13)
    at _LocaleContainer (http://localhost:8000/umi.js:3250:31)
    at http://localhost:8000/umi.js:3970:23
```

使用代码
```
import React from 'react';
import TreeTable from 'react-antd-treetable';

const data = [
  {
    name: 'foo',
    children: [
      {
        name: 'bar',
      },
    ],
  },
];

const columns = [
  {
    title: '名称',
    dataIndex: 'name',
  },
];

const App = () => {
  return <TreeTable rowKey="id" dataSource={data} columns={columns} />;
};

export default App;
```

**Comment by sl1673495** [comment]
这个看起来是 umi 的 mfsu 功能导致的问题，你试着把 umi 配置里的 mfsu 关掉重启试试？如果是他们那边的问题的话，可以给 umi 提个 issue。

**Comment by sl1673495** [comment]
![image](https://user-images.githubusercontent.com/23615778/125250311-a9173700-e328-11eb-8fa5-85b9990725ba.png)
umi 的这个功能好像要求 3.5 版本以上？

**Comment by daisybaicai** [comment]
可以了，就是mfsu的问题。那个版本是我package.json复制的，实际上应该是umi@3.5.3
